In [4]:
import numpy as np
dataset = np.loadtxt('./data/{}.csv'.format(r'759'), delimiter=',')

In [5]:
dataset

array([[1.        , 0.56097235, 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.51088553, 0.        , ..., 0.        , 1.        ,
        1.        ],
       [0.        , 0.74248698, 0.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [1.        , 0.58260986, 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.45131561, 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.2906371 , 1.        , ..., 0.        , 1.        ,
        0.        ]])

In [6]:
import pandas as pd
import numpy as np

# Assuming data_file is defined
data_file = 'your_file_name'  # Replace with your actual file name without .csv extension

# Load the CSV file using pandas
df = pd.read_csv('./data/{}.csv'.format('759'))

# Convert the DataFrame to a numpy array
dataset = df.values

# Now dataset is a numpy array similar to what np.loadtxt would produce

In [8]:
df

,1.0,0.5609723520769334,1.0.1,0.0,0.0.1,0.0.2,0.0.3,0.0.4,0.0.5,0.0.6,...,0.0.14,0.0.15,0.0.16,0.0.17,0.0.18,0.0.19,0.0.20,0.0.21,1.0.2,0
0,0.0,0.510886,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
1,0.0,0.742487,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
2,0.0,0.624416,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
3,1.0,0.322826,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
4,1.0,0.555630,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
833,0.0,0.260585,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
834,0.0,0.357820,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
835,1.0,0.582610,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
836,1.0,0.451316,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
837,0.0,0.290637,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0

In [7]:
dataset

array([[0.        , 0.51088553, 0.        , ..., 0.        , 1.        ,
        1.        ],
       [0.        , 0.74248698, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.62441565, 1.        , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [1.        , 0.58260986, 1.        , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.45131561, 1.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.2906371 , 1.        , ..., 0.        , 1.        ,
        0.        ]])